services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_e2e
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - e2e-network

  authentication-service-mongodb:
    container_name: authentication_service_mongodb_e2e
    volumes: []
    # Use tmpfs for faster I/O in tests
    tmpfs:
      - /data/db
    networks:
      - e2e-network

  authentication-service:
    container_name: authentication_service_e2e
    depends_on:
      authentication-service-mongodb:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    networks:
      - e2e-network

  api-gateway:
    container_name: api_gateway_e2e
    environment:
      NODE_ENV: test
      AUTHENTICATION_SERVICE_URL: http://authentication-service:3000
    networks:
      - e2e-network

  frontend:
    container_name: frontend_e2e
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - e2e-network

networks:
  e2e-network:
    driver: bridge
